docker_repo_url: "https://download.docker.com/linux/debian"
docker_gpg_url: "https://download.docker.com/linux/debian/gpg"

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_conflicting_packages:
  - docker.io
  - docker-compose
  - docker-doc
  - podman-docker
  - containerd
  - runc