---
- name: Add selected user keys to root
  ansible.posix.authorized_key:
    user: root
    key: "{{ item.value.ssh_keys | join('\n') }}"
    state: present
  loop: "{{ users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - item.value.add_keys_to_root | default(false) | bool
    - item.value.state | default('present') == 'present'
    - item.value.ssh_keys is defined
    - >
      'all' in (item.value.targets | default([]))
      or inventory_hostname in (item.value.targets | default([]))
      or ((item.value.targets | default([])) | intersect(group_names) | length > 0)

- name: Remove keys from root for absent users
  ansible.posix.authorized_key:
    user: root
    key: "{{ item.value.ssh_keys | join('\n') }}"
    state: absent
  loop: "{{ users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - item.value.add_keys_to_root | default(false) | bool
    - item.value.state | default('present') == 'absent'
    - item.value.ssh_keys is defined
    - >
      'all' in (item.value.targets | default([]))
      or inventory_hostname in (item.value.targets | default([]))
      or ((item.value.targets | default([])) | intersect(group_names) | length > 0)