apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: website
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: 80
            initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
            failureThreshold: {{ .Values.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: 80
            initialDelaySeconds: 5
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
            failureThreshold: {{ .Values.healthCheck.failureThreshold }}
