- name: Install local-path provisioner
  ansible.builtin.shell: >
    kubectl apply -f
    https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
  changed_when: true

- name: Set local-path as default StorageClass
  ansible.builtin.shell: >
    kubectl annotate storageclass local-path
    storageclass.kubernetes.io/is-default-class=true
    --overwrite
  changed_when: true

- name: Wait for local-path provisioner deployment
  ansible.builtin.shell: >
    kubectl rollout status deployment/local-path-provisioner
    -n local-path-storage --timeout=120s
  changed_when: false