{
 "title": "Network Reachability",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "label_values(probe_success, location)"
   }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response Code ($location)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "repeat": "location",
   "targets": [
    {
     "expr": "probe_http_status_code{job=~\"integrations/blackbox/.+\", location=~\"$location\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Response time ($location)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "repeat": "location",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~\"integrations/blackbox/.+\", location=~\"$location\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "TLS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "TLS Certificates",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "probe_ssl_earliest_cert_expiry" }
   ]
  }
 ]
}