apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-alloy.fullname" . }}-config
  labels:
    {{- include "grafana-alloy.labels" . | nindent 4 }}
data:
  config.alloy: |
    {{- tpl (.Files.Get "config/config.alloy") . | nindent 4 }}
