apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mimir.fullname" . }}-config
  labels:
    {{- include "mimir.labels" . | nindent 4 }}
data:
  mimir.yaml: |
    {{- tpl (.Files.Get "config/mimir.yaml") . | nindent 4 }}
