apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mimir.fullname" . }}-data
  labels:
    {{- include "mimir.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
