- name: Check if control plane already joined
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_admin_conf

- name: Join node as additional control plane
  ansible.builtin.command: >
    {{ hostvars[groups['control_plane'][0]].control_plane_join_command }}
    --cri-socket unix:///run/containerd/containerd.sock
  when: not k8s_admin_conf.stat.exists

- name: Ensure root kubeconfig dir exists
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: "0700"

- name: Copy admin.conf to root kubeconfig
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    mode: "0600"
  when: k8s_admin_conf.stat.exists