- name: Join additional control planes
  hosts: control_plane
  become: true
  tasks:
    - name: Join node as additional control plane
      ansible.builtin.include_role:
        name: k8s_control_plane_join
      when: not (k8s_control_plane_bootstrap | default(false) | bool)