- import_playbook: hosts.yml
- import_playbook: 08-users.yml
- import_playbook: 01-bootstrap-k8s.yml
- import_playbook: 02-init-control-plane.yml
- import_playbook: 05-install-cni-flannel.yml
- import_playbook: 03-join-workers.yml
- import_playbook: 04-join-control-planes.yml