http:
  routers:
    alerta-http:
      rule: "Host(`alerta.swasilewski.pl`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: alerta

    alerta-https:
      rule: "Host(`alerta.swasilewski.pl`)"
      entryPoints:
        - websecure
      service: alerta
      tls:
        certResolver: le

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https

  services:
    alerta:
      loadBalancer:
        servers:
          - url: "http://10.10.10.82:30097"
          - url: "http://10.10.10.83:30097"
          - url: "http://10.10.10.84:30097"
