apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-admin
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.admin.user | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.admin.password | quote }}
