apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager.fullname" . }}-config
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
data:
  alertmanager.yml: |
    {{- tpl (.Files.Get "config/alertmanager.yml") . | nindent 4 }}
