apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-state-metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-state-metrics.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kube-state-metrics.fullname" . }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: kube-state-metrics
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-metrics
              containerPort: 8080
            - name: telemetry
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
